// Code generated by go-enum DO NOT EDIT.
// Version:
// Revision:
// Build Date:
// Built By:

package constants

import (
	"errors"
	"fmt"
)

const (
	// ErrorCodeApiError is a ErrorCode of type api_error.
	ErrorCodeApiError ErrorCode = "api_error"
	// ErrorCodeValidationError is a ErrorCode of type validation_error.
	ErrorCodeValidationError ErrorCode = "validation_error"
)

var ErrInvalidErrorCode = errors.New("not a valid ErrorCode")

// String implements the Stringer interface.
func (x ErrorCode) String() string {
	return string(x)
}

// String implements the Stringer interface.
func (x ErrorCode) IsValid() bool {
	_, err := ParseErrorCode(string(x))
	return err == nil
}

var _ErrorCodeValue = map[string]ErrorCode{
	"api_error":        ErrorCodeApiError,
	"validation_error": ErrorCodeValidationError,
}

// ParseErrorCode attempts to convert a string to a ErrorCode.
func ParseErrorCode(name string) (ErrorCode, error) {
	if x, ok := _ErrorCodeValue[name]; ok {
		return x, nil
	}
	return ErrorCode(""), fmt.Errorf("%s is %w", name, ErrInvalidErrorCode)
}
