// Code generated by go-enum DO NOT EDIT.
// Version:
// Revision:
// Build Date:
// Built By:

package constants

import (
	"errors"
	"fmt"
)

const (
	// ServiceNameAquaBackend is a ServiceName of type aqua-backend.
	ServiceNameAquaBackend ServiceName = "aqua-backend"
)

var ErrInvalidServiceName = errors.New("not a valid ServiceName")

// String implements the Stringer interface.
func (x ServiceName) String() string {
	return string(x)
}

// String implements the Stringer interface.
func (x ServiceName) IsValid() bool {
	_, err := ParseServiceName(string(x))
	return err == nil
}

var _ServiceNameValue = map[string]ServiceName{
	"aqua-backend": ServiceNameAquaBackend,
}

// ParseServiceName attempts to convert a string to a ServiceName.
func ParseServiceName(name string) (ServiceName, error) {
	if x, ok := _ServiceNameValue[name]; ok {
		return x, nil
	}
	return ServiceName(""), fmt.Errorf("%s is %w", name, ErrInvalidServiceName)
}
